// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_slug_ from "./routes/api/[...slug].tsx";
import * as $docs_slug_ from "./routes/docs/[...slug].tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $ontology_IRI from "./routes/ontology/IRI.tsx";
import * as $ontology_Resource from "./routes/ontology/Resource.tsx";
import * as $ontology_index from "./routes/ontology/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[...slug].tsx": $api_slug_,
    "./routes/docs/[...slug].tsx": $docs_slug_,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
    "./routes/ontology/IRI.tsx": $ontology_IRI,
    "./routes/ontology/Resource.tsx": $ontology_Resource,
    "./routes/ontology/index.tsx": $ontology_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
