# This workflow will run tests using Deno

name: Test using Deno

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fmt-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task fmt:check
      - run: deno task lint
      - run: deno task test
      - run: deno task dnt
